---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/deploy"
    pipelinesascode.tekton.dev/task: "https://github.com/rh-hackathon-2024/autodevops-cd-manifests/blob/main/tasks/task-verify-app-health.yaml"
    pipelinesascode.tekton.dev/task-1: "https://github.com/rh-hackathon-2024/autodevops-cd-manifests/blob/main/tasks/task-sync-argo-app.yaml"
    pipelinesascode.tekton.dev/task-2: "https://github.com/rh-hackathon-2024/autodevops-cd-manifests/blob/main/tasks/task-get-routes.yaml"
    pipelinesascode.tekton.dev/task-3: "[github-add-comment]"
spec:
  params:
    - name: repo-url
      value: "{{repo_url}}"
  pipelineSpec:
    params:
    - name: repo-url
    tasks:
    - name: verify-app-health
      params:
        - name: application-name
          value: "{{ repo_name }}"
      taskRef:
        kind: Task
        name: verify-app-health
    - name: sync-argo-app
      params:
        - name: application-name
          value: "{{ repo_name }}"
      runAfter:
        - verify-app-health
      taskRef:
        kind: Task
        name: sync-argo-app
    - name: get-app-endpoint
      params:
        - name: SCRIPT
          value: |
            "oc get route go-app-route --template='http://{{.spec.host}}:{{.spec.port.targetPort}}{{.spec.path}}'"
        - name: VERSION
          value: latest
      runAfter:
        - sync-argo-app
      taskRef:
        kind: Task
        name: openshift-client
    - name: publish-status-to-github
      params:
        - name: REQUEST_URL
          value: $(params.repo-url)/pull/{{ pull_request_number }}
        - name: COMMENT_OR_FILE
          value: |
            Application status is $(tasks.sync-argo-app.results.HEALTH_STATUS).
            You can access the application using the following link $(tasks.get-app-endpoint.results.output)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: "{{ git_auth_secret }}"
        - name: GITHUB_TOKEN_SECRET_KEY
          value: "git-provider-token"
      runAfter:
        - sync-argo-app
        - get-app-endpoint
      taskRef:
        kind: Task
        name: github-add-commenit


