apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: openshift-gitops-server.openshift-gitops.svc.cluster.local:443
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: YWRtaW4=  
  ARGOCD_PASSWORD: <password>
  #ARGOCD_AUTH_TOKEN: <token>
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: argocd-pipeline-autodevops
spec:
  tasks:
    - name: refresh-app
      taskRef:
        name: argocd-task-app-refresh
      params:
        - name: application-name
          value: hello-world-app
    - name: check-diff
      taskRef:
        name: argocd-task-check-diff-sync
      runAfter: 
        - refresh-app
      params:
        - name: application-name
          value: hello-world-app
        - name: flags
          value: --insecure # needed in this example only because the Argo CD server is locally hosted
