apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      argocds.argoproj.io/name: openshift-gitops
      argocds.argoproj.io/namespace: openshift-gitops
    labels:
      app.kubernetes.io/managed-by: openshift-gitops
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
    name: openshift-gitops-argocd-application-controller
    namespace: demo
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: openshift-gitops-argocd-application-controller
  subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      argocds.argoproj.io/name: openshift-gitops
      argocds.argoproj.io/namespace: openshift-gitops
    creationTimestamp: "2024-06-25T06:24:14Z"
    labels:
      app.kubernetes.io/managed-by: openshift-gitops
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
    name: openshift-gitops-argocd-server
    namespace: demo
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: openshift-gitops-argocd-server
  subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: openshift-gitops
kind: List
metadata:
  resourceVersion: ""